FROM gradle:8.5-jdk21 AS build

ARG DB_URL
ENV DB_URL=$DB_URL
ARG FIREBASE_ACCESS_KEY
ENV FIREBASE_ACCESS_KEY=$FIREBASE_ACCESS_KEY
ARG PROJECT_ACCESS_KEY
ENV PROJECT_ACCESS_KEY=$PROJECT_ACCESS_KEY
ARG GOOGLE_PROJECT_ID
ENV GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID
ARG BUCKET_NAME
ENV BUCKET_NAME=$BUCKET_NAME
ARG SENTRY_DSN
ENV SENTRY_DSN=$SENTRY_DSN
ARG SENTRY_ENV
ENV SENTRY_ENV=$SENTRY_ENV

COPY . /app
WORKDIR /app
RUN apt-get update && apt-get install -y maven
RUN chmod +x ./gradlew
RUN ./gradlew clean build -x test

FROM openjdk:21 AS final
COPY --from=build /app/build/libs/api.jar /app/api.jar
EXPOSE 80
CMD ["java", "-jar", "/app/api.jar"]
