openapi: 3.0.3
info:
  version: "latest"
  title: API
  description: This API provides access to the Hackoholics service.
servers:
  - url: "http://localhost:8080"

paths:
  /ping:
    get:
      tags:
        - Health
      summary: Health check
      operationId: ping
      description: Check server health
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
        500:
          $ref: "#/components/responses/500"

  /signin:
    post:
      tags:
        - Security
      summary: Login user.
      operationId: signIn
      security: [ BearerToken: {} ]
      responses:
        "201":
          description: Authenticated User
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "429":
          $ref: "#/components/responses/429"
        "500":
          $ref: "#/components/responses/500"

  /signup:
    post:
      tags:
        - Security
      summary: Sign up user
      operationId: signUp
      requestBody:
        description: User to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: Signed up user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "429":
          $ref: "#/components/responses/429"
        "500":
          $ref: "#/components/responses/500"

components:
  responses:
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestException"
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotAuthorizedException"
    404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResourceNotFoundException"
    429:
      description: Too many requests to the API
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TooManyRequestsException"
    500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerException"
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        firebaseId:
          type: string
        email:
          type: string
        photoId:
          type: string

    Page:
      type: integer
      description: Start at `1`
    PageSize:
      type: integer
      description: Cannot exceed `500`
    Exception:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    BadRequestException:
      allOf:
        - $ref: "#/components/schemas/Exception"
    NotAuthorizedException:
      allOf:
        - $ref: "#/components/schemas/Exception"
    ResourceNotFoundException:
      allOf:
        - $ref: "#/components/schemas/Exception"
    TooManyRequestsException:
      allOf:
        - $ref: "#/components/schemas/Exception"
    InternalServerException:
      allOf:
        - $ref: "#/components/schemas/Exception"